// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH6_5C2nJNFyjsvf0Cgl0fQtl5YBlLfto',
    appId: '1:249095252709:web:199cc59e4f4ea5257c820c',
    messagingSenderId: '249095252709',
    projectId: 'utrivia-58e0c',
    authDomain: 'utrivia-58e0c.firebaseapp.com',
    storageBucket: 'utrivia-58e0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhi1t0vuT_Wfh_ahH0J9ZVlENRydp50Y',
    appId: '1:249095252709:android:7ebc765e1c445bd97c820c',
    messagingSenderId: '249095252709',
    projectId: 'utrivia-58e0c',
    storageBucket: 'utrivia-58e0c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH6_5C2nJNFyjsvf0Cgl0fQtl5YBlLfto',
    appId: '1:249095252709:web:199cc59e4f4ea5257c820c',
    messagingSenderId: '249095252709',
    projectId: 'utrivia-58e0c',
    authDomain: 'utrivia-58e0c.firebaseapp.com',
    storageBucket: 'utrivia-58e0c.firebasestorage.app',
  );
}
