import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'screens/register_page.dart'; // I-import ang iyong register page

Future<void> main() async {
  // Required before any async work happens prior to runApp()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the config generated for your project
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const UTriviaApp());
}

class UTriviaApp extends StatelessWidget {
  const UTriviaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'U-TRIVIA',
      debugShowCheckedModeBanner: false,
      // I-configure ang Light Theme para hindi maging dark/itim ang mga screen at text
      theme: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.green,
        scaffoldBackgroundColor: const Color(0xFFF3F4F6), // Light background
        fontFamily: 'Roboto',
      ),
      // Para siguruhing hindi susunod sa dark mode ng phone o emulator:
      darkTheme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: const Color(0xFFF3F4F6),
      ),
      themeMode: ThemeMode.light,
      home: const RegisterPage(), // Naka-set na dito ang Register Page mo
    );
  }
}
